export type BannerPreset = { id: string; name: string; url: string; category: "colors" | "flags" | "music" };

export const COLOR_BANNERS: BannerPreset[] = [
  { id: "champagne-frost-pearl", name: "Champagne Frost Pearl", url: "/banners/color-champagne.jpg", category: "colors" },
  { id: "silver", name: "Silver", url: "/banners/color-silver.jpg", category: "colors" },
  { id: "gold-luxe", name: "Gold Luxe", url: "/banners/color-gold.jpg", category: "colors" },
  { id: "pearl-white", name: "Pearl White", url: "/banners/color-pearl.jpg", category: "colors" },
  { id: "frost-blue", name: "Frost Blue", url: "/banners/color-frost.jpg", category: "colors" },
  { id: "midnight", name: "Midnight", url: "/banners/color-midnight.jpg", category: "colors" },
  { id: "rose-quartz", name: "Rose Quartz", url: "/banners/color-rose.jpg", category: "colors" },
  { id: "emerald", name: "Emerald", url: "/banners/color-emerald.jpg", category: "colors" },
  { id: "amethyst", name: "Amethyst", url: "/banners/color-amethyst.jpg", category: "colors" },
  { id: "obsidian", name: "Obsidian", url: "/banners/color-obsidian.jpg", category: "colors" },
  { id: "copper", name: "Copper", url: "/banners/color-copper.jpg", category: "colors" },
  { id: "rainbow", name: "Rainbow", url: "/banners/color-rainbow.jpg", category: "colors" },
  { id: "ocean", name: "Ocean", url: "/banners/color-ocean.jpg", category: "colors" },
  { id: "sunset", name: "Sunset", url: "/banners/color-sunset.jpg", category: "colors" },
];

export const MUSIC_BANNERS: BannerPreset[] = [
  { id: "music-champagne-mix", name: "Champagne · Guitar Violin Sax Trumpet", url: "/banners/music-champagne-mix.jpg", category: "music" },
  { id: "music-navy-studio", name: "Navy · Piano Mic Headphones Drums", url: "/banners/music-navy-studio.jpg", category: "music" },
  { id: "music-rosewood-strings", name: "Rosewood · Violin Flute Cello", url: "/banners/music-rosewood-strings.jpg", category: "music" },
  { id: "music-black-gold-rock", name: "Black Gold · Guitar Sax Trumpet Drums", url: "/banners/music-black-gold-rock.jpg", category: "music" },
  { id: "music-pearl-orchestra", name: "Pearl · Harp Accordion Clarinet Horn", url: "/banners/music-pearl-orchestra.jpg", category: "music" },
  { id: "music-emerald-brass", name: "Emerald · Cello Trombone Tambourine", url: "/banners/music-emerald-brass.jpg", category: "music" },
];

export const FLAG_BANNERS: BannerPreset[] = [
  { id: "flag-ad", name: "Andorra", url: "/banners/flags/ad.jpg", category: "flags" },
  { id: "flag-ae", name: "United Arab Emirates", url: "/banners/flags/ae.jpg", category: "flags" },
  { id: "flag-af", name: "Afghanistan", url: "/banners/flags/af.jpg", category: "flags" },
  { id: "flag-ag", name: "Antigua and Barbuda", url: "/banners/flags/ag.jpg", category: "flags" },
  { id: "flag-ai", name: "Anguilla", url: "/banners/flags/ai.jpg", category: "flags" },
  { id: "flag-al", name: "Albania", url: "/banners/flags/al.jpg", category: "flags" },
  { id: "flag-am", name: "Armenia", url: "/banners/flags/am.jpg", category: "flags" },
  { id: "flag-ao", name: "Angola", url: "/banners/flags/ao.jpg", category: "flags" },
  { id: "flag-aq", name: "Antarctica", url: "/banners/flags/aq.jpg", category: "flags" },
  { id: "flag-ar", name: "Argentina", url: "/banners/flags/ar.jpg", category: "flags" },
  { id: "flag-as", name: "American Samoa", url: "/banners/flags/as.jpg", category: "flags" },
  { id: "flag-at", name: "Austria", url: "/banners/flags/at.jpg", category: "flags" },
  { id: "flag-au", name: "Australia", url: "/banners/flags/au.jpg", category: "flags" },
  { id: "flag-aw", name: "Aruba", url: "/banners/flags/aw.jpg", category: "flags" },
  { id: "flag-ax", name: "Åland Islands", url: "/banners/flags/ax.jpg", category: "flags" },
  { id: "flag-az", name: "Azerbaijan", url: "/banners/flags/az.jpg", category: "flags" },
  { id: "flag-ba", name: "Bosnia and Herzegovina", url: "/banners/flags/ba.jpg", category: "flags" },
  { id: "flag-bb", name: "Barbados", url: "/banners/flags/bb.jpg", category: "flags" },
  { id: "flag-bd", name: "Bangladesh", url: "/banners/flags/bd.jpg", category: "flags" },
  { id: "flag-be", name: "Belgium", url: "/banners/flags/be.jpg", category: "flags" },
  { id: "flag-bf", name: "Burkina Faso", url: "/banners/flags/bf.jpg", category: "flags" },
  { id: "flag-bg", name: "Bulgaria", url: "/banners/flags/bg.jpg", category: "flags" },
  { id: "flag-bh", name: "Bahrain", url: "/banners/flags/bh.jpg", category: "flags" },
  { id: "flag-bi", name: "Burundi", url: "/banners/flags/bi.jpg", category: "flags" },
  { id: "flag-bj", name: "Benin", url: "/banners/flags/bj.jpg", category: "flags" },
  { id: "flag-bl", name: "Saint Barthélemy", url: "/banners/flags/bl.jpg", category: "flags" },
  { id: "flag-bm", name: "Bermuda", url: "/banners/flags/bm.jpg", category: "flags" },
  { id: "flag-bn", name: "Brunei", url: "/banners/flags/bn.jpg", category: "flags" },
  { id: "flag-bo", name: "Bolivia", url: "/banners/flags/bo.jpg", category: "flags" },
  { id: "flag-bq", name: "Caribbean Netherlands", url: "/banners/flags/bq.jpg", category: "flags" },
  { id: "flag-br", name: "Brazil", url: "/banners/flags/br.jpg", category: "flags" },
  { id: "flag-bs", name: "Bahamas", url: "/banners/flags/bs.jpg", category: "flags" },
  { id: "flag-bt", name: "Bhutan", url: "/banners/flags/bt.jpg", category: "flags" },
  { id: "flag-bv", name: "Bouvet Island", url: "/banners/flags/bv.jpg", category: "flags" },
  { id: "flag-bw", name: "Botswana", url: "/banners/flags/bw.jpg", category: "flags" },
  { id: "flag-by", name: "Belarus", url: "/banners/flags/by.jpg", category: "flags" },
  { id: "flag-bz", name: "Belize", url: "/banners/flags/bz.jpg", category: "flags" },
  { id: "flag-ca", name: "Canada", url: "/banners/flags/ca.jpg", category: "flags" },
  { id: "flag-cc", name: "Cocos Islands", url: "/banners/flags/cc.jpg", category: "flags" },
  { id: "flag-cd", name: "DR Congo", url: "/banners/flags/cd.jpg", category: "flags" },
  { id: "flag-cf", name: "Central African Republic", url: "/banners/flags/cf.jpg", category: "flags" },
  { id: "flag-cg", name: "Congo", url: "/banners/flags/cg.jpg", category: "flags" },
  { id: "flag-ch", name: "Switzerland", url: "/banners/flags/ch.jpg", category: "flags" },
  { id: "flag-ci", name: "Côte d'Ivoire", url: "/banners/flags/ci.jpg", category: "flags" },
  { id: "flag-ck", name: "Cook Islands", url: "/banners/flags/ck.jpg", category: "flags" },
  { id: "flag-cl", name: "Chile", url: "/banners/flags/cl.jpg", category: "flags" },
  { id: "flag-cm", name: "Cameroon", url: "/banners/flags/cm.jpg", category: "flags" },
  { id: "flag-cn", name: "China", url: "/banners/flags/cn.jpg", category: "flags" },
  { id: "flag-co", name: "Colombia", url: "/banners/flags/co.jpg", category: "flags" },
  { id: "flag-cr", name: "Costa Rica", url: "/banners/flags/cr.jpg", category: "flags" },
  { id: "flag-cu", name: "Cuba", url: "/banners/flags/cu.jpg", category: "flags" },
  { id: "flag-cv", name: "Cape Verde", url: "/banners/flags/cv.jpg", category: "flags" },
  { id: "flag-cw", name: "Curaçao", url: "/banners/flags/cw.jpg", category: "flags" },
  { id: "flag-cx", name: "Christmas Island", url: "/banners/flags/cx.jpg", category: "flags" },
  { id: "flag-cy", name: "Cyprus", url: "/banners/flags/cy.jpg", category: "flags" },
  { id: "flag-cz", name: "Czechia", url: "/banners/flags/cz.jpg", category: "flags" },
  { id: "flag-de", name: "Germany", url: "/banners/flags/de.jpg", category: "flags" },
  { id: "flag-dj", name: "Djibouti", url: "/banners/flags/dj.jpg", category: "flags" },
  { id: "flag-dk", name: "Denmark", url: "/banners/flags/dk.jpg", category: "flags" },
  { id: "flag-dm", name: "Dominica", url: "/banners/flags/dm.jpg", category: "flags" },
  { id: "flag-do", name: "Dominican Republic", url: "/banners/flags/do.jpg", category: "flags" },
  { id: "flag-dz", name: "Algeria", url: "/banners/flags/dz.jpg", category: "flags" },
  { id: "flag-ec", name: "Ecuador", url: "/banners/flags/ec.jpg", category: "flags" },
  { id: "flag-ee", name: "Estonia", url: "/banners/flags/ee.jpg", category: "flags" },
  { id: "flag-eg", name: "Egypt", url: "/banners/flags/eg.jpg", category: "flags" },
  { id: "flag-eh", name: "Western Sahara", url: "/banners/flags/eh.jpg", category: "flags" },
  { id: "flag-er", name: "Eritrea", url: "/banners/flags/er.jpg", category: "flags" },
  { id: "flag-es", name: "Spain", url: "/banners/flags/es.jpg", category: "flags" },
  { id: "flag-et", name: "Ethiopia", url: "/banners/flags/et.jpg", category: "flags" },
  { id: "flag-fi", name: "Finland", url: "/banners/flags/fi.jpg", category: "flags" },
  { id: "flag-fj", name: "Fiji", url: "/banners/flags/fj.jpg", category: "flags" },
  { id: "flag-fk", name: "Falkland Islands", url: "/banners/flags/fk.jpg", category: "flags" },
  { id: "flag-fm", name: "Micronesia", url: "/banners/flags/fm.jpg", category: "flags" },
  { id: "flag-fo", name: "Faroe Islands", url: "/banners/flags/fo.jpg", category: "flags" },
  { id: "flag-fr", name: "France", url: "/banners/flags/fr.jpg", category: "flags" },
  { id: "flag-ga", name: "Gabon", url: "/banners/flags/ga.jpg", category: "flags" },
  { id: "flag-gb", name: "United Kingdom", url: "/banners/flags/gb.jpg", category: "flags" },
  { id: "flag-gd", name: "Grenada", url: "/banners/flags/gd.jpg", category: "flags" },
  { id: "flag-ge", name: "Georgia", url: "/banners/flags/ge.jpg", category: "flags" },
  { id: "flag-gf", name: "French Guiana", url: "/banners/flags/gf.jpg", category: "flags" },
  { id: "flag-gg", name: "Guernsey", url: "/banners/flags/gg.jpg", category: "flags" },
  { id: "flag-gh", name: "Ghana", url: "/banners/flags/gh.jpg", category: "flags" },
  { id: "flag-gi", name: "Gibraltar", url: "/banners/flags/gi.jpg", category: "flags" },
  { id: "flag-gl", name: "Greenland", url: "/banners/flags/gl.jpg", category: "flags" },
  { id: "flag-gm", name: "Gambia", url: "/banners/flags/gm.jpg", category: "flags" },
  { id: "flag-gn", name: "Guinea", url: "/banners/flags/gn.jpg", category: "flags" },
  { id: "flag-gp", name: "Guadeloupe", url: "/banners/flags/gp.jpg", category: "flags" },
  { id: "flag-gq", name: "Equatorial Guinea", url: "/banners/flags/gq.jpg", category: "flags" },
  { id: "flag-gr", name: "Greece", url: "/banners/flags/gr.jpg", category: "flags" },
  { id: "flag-gs", name: "South Georgia", url: "/banners/flags/gs.jpg", category: "flags" },
  { id: "flag-gt", name: "Guatemala", url: "/banners/flags/gt.jpg", category: "flags" },
  { id: "flag-gu", name: "Guam", url: "/banners/flags/gu.jpg", category: "flags" },
  { id: "flag-gw", name: "Guinea-Bissau", url: "/banners/flags/gw.jpg", category: "flags" },
  { id: "flag-gy", name: "Guyana", url: "/banners/flags/gy.jpg", category: "flags" },
  { id: "flag-hk", name: "Hong Kong", url: "/banners/flags/hk.jpg", category: "flags" },
  { id: "flag-hm", name: "Heard Island", url: "/banners/flags/hm.jpg", category: "flags" },
  { id: "flag-hn", name: "Honduras", url: "/banners/flags/hn.jpg", category: "flags" },
  { id: "flag-hr", name: "Croatia", url: "/banners/flags/hr.jpg", category: "flags" },
  { id: "flag-ht", name: "Haiti", url: "/banners/flags/ht.jpg", category: "flags" },
  { id: "flag-hu", name: "Hungary", url: "/banners/flags/hu.jpg", category: "flags" },
  { id: "flag-id", name: "Indonesia", url: "/banners/flags/id.jpg", category: "flags" },
  { id: "flag-ie", name: "Ireland", url: "/banners/flags/ie.jpg", category: "flags" },
  { id: "flag-il", name: "Israel", url: "/banners/flags/il.jpg", category: "flags" },
  { id: "flag-im", name: "Isle of Man", url: "/banners/flags/im.jpg", category: "flags" },
  { id: "flag-in", name: "India", url: "/banners/flags/in.jpg", category: "flags" },
  { id: "flag-io", name: "British Indian Ocean Territory", url: "/banners/flags/io.jpg", category: "flags" },
  { id: "flag-iq", name: "Iraq", url: "/banners/flags/iq.jpg", category: "flags" },
  { id: "flag-ir", name: "Iran", url: "/banners/flags/ir.jpg", category: "flags" },
  { id: "flag-is", name: "Iceland", url: "/banners/flags/is.jpg", category: "flags" },
  { id: "flag-it", name: "Italy", url: "/banners/flags/it.jpg", category: "flags" },
  { id: "flag-je", name: "Jersey", url: "/banners/flags/je.jpg", category: "flags" },
  { id: "flag-jm", name: "Jamaica", url: "/banners/flags/jm.jpg", category: "flags" },
  { id: "flag-jo", name: "Jordan", url: "/banners/flags/jo.jpg", category: "flags" },
  { id: "flag-jp", name: "Japan", url: "/banners/flags/jp.jpg", category: "flags" },
  { id: "flag-ke", name: "Kenya", url: "/banners/flags/ke.jpg", category: "flags" },
  { id: "flag-kg", name: "Kyrgyzstan", url: "/banners/flags/kg.jpg", category: "flags" },
  { id: "flag-kh", name: "Cambodia", url: "/banners/flags/kh.jpg", category: "flags" },
  { id: "flag-ki", name: "Kiribati", url: "/banners/flags/ki.jpg", category: "flags" },
  { id: "flag-km", name: "Comoros", url: "/banners/flags/km.jpg", category: "flags" },
  { id: "flag-kn", name: "Saint Kitts and Nevis", url: "/banners/flags/kn.jpg", category: "flags" },
  { id: "flag-kp", name: "North Korea", url: "/banners/flags/kp.jpg", category: "flags" },
  { id: "flag-kr", name: "South Korea", url: "/banners/flags/kr.jpg", category: "flags" },
  { id: "flag-kw", name: "Kuwait", url: "/banners/flags/kw.jpg", category: "flags" },
  { id: "flag-ky", name: "Cayman Islands", url: "/banners/flags/ky.jpg", category: "flags" },
  { id: "flag-kz", name: "Kazakhstan", url: "/banners/flags/kz.jpg", category: "flags" },
  { id: "flag-la", name: "Laos", url: "/banners/flags/la.jpg", category: "flags" },
  { id: "flag-lb", name: "Lebanon", url: "/banners/flags/lb.jpg", category: "flags" },
  { id: "flag-lc", name: "Saint Lucia", url: "/banners/flags/lc.jpg", category: "flags" },
  { id: "flag-li", name: "Liechtenstein", url: "/banners/flags/li.jpg", category: "flags" },
  { id: "flag-lk", name: "Sri Lanka", url: "/banners/flags/lk.jpg", category: "flags" },
  { id: "flag-lr", name: "Liberia", url: "/banners/flags/lr.jpg", category: "flags" },
  { id: "flag-ls", name: "Lesotho", url: "/banners/flags/ls.jpg", category: "flags" },
  { id: "flag-lt", name: "Lithuania", url: "/banners/flags/lt.jpg", category: "flags" },
  { id: "flag-lu", name: "Luxembourg", url: "/banners/flags/lu.jpg", category: "flags" },
  { id: "flag-lv", name: "Latvia", url: "/banners/flags/lv.jpg", category: "flags" },
  { id: "flag-ly", name: "Libya", url: "/banners/flags/ly.jpg", category: "flags" },
  { id: "flag-ma", name: "Morocco", url: "/banners/flags/ma.jpg", category: "flags" },
  { id: "flag-mc", name: "Monaco", url: "/banners/flags/mc.jpg", category: "flags" },
  { id: "flag-md", name: "Moldova", url: "/banners/flags/md.jpg", category: "flags" },
  { id: "flag-me", name: "Montenegro", url: "/banners/flags/me.jpg", category: "flags" },
  { id: "flag-mf", name: "Saint Martin", url: "/banners/flags/mf.jpg", category: "flags" },
  { id: "flag-mg", name: "Madagascar", url: "/banners/flags/mg.jpg", category: "flags" },
  { id: "flag-mh", name: "Marshall Islands", url: "/banners/flags/mh.jpg", category: "flags" },
  { id: "flag-mk", name: "North Macedonia", url: "/banners/flags/mk.jpg", category: "flags" },
  { id: "flag-ml", name: "Mali", url: "/banners/flags/ml.jpg", category: "flags" },
  { id: "flag-mm", name: "Myanmar", url: "/banners/flags/mm.jpg", category: "flags" },
  { id: "flag-mn", name: "Mongolia", url: "/banners/flags/mn.jpg", category: "flags" },
  { id: "flag-mo", name: "Macao", url: "/banners/flags/mo.jpg", category: "flags" },
  { id: "flag-mp", name: "Northern Mariana Islands", url: "/banners/flags/mp.jpg", category: "flags" },
  { id: "flag-mq", name: "Martinique", url: "/banners/flags/mq.jpg", category: "flags" },
  { id: "flag-mr", name: "Mauritania", url: "/banners/flags/mr.jpg", category: "flags" },
  { id: "flag-ms", name: "Montserrat", url: "/banners/flags/ms.jpg", category: "flags" },
  { id: "flag-mt", name: "Malta", url: "/banners/flags/mt.jpg", category: "flags" },
  { id: "flag-mu", name: "Mauritius", url: "/banners/flags/mu.jpg", category: "flags" },
  { id: "flag-mv", name: "Maldives", url: "/banners/flags/mv.jpg", category: "flags" },
  { id: "flag-mw", name: "Malawi", url: "/banners/flags/mw.jpg", category: "flags" },
  { id: "flag-mx", name: "Mexico", url: "/banners/flags/mx.jpg", category: "flags" },
  { id: "flag-my", name: "Malaysia", url: "/banners/flags/my.jpg", category: "flags" },
  { id: "flag-mz", name: "Mozambique", url: "/banners/flags/mz.jpg", category: "flags" },
  { id: "flag-na", name: "Namibia", url: "/banners/flags/na.jpg", category: "flags" },
  { id: "flag-nc", name: "New Caledonia", url: "/banners/flags/nc.jpg", category: "flags" },
  { id: "flag-ne", name: "Niger", url: "/banners/flags/ne.jpg", category: "flags" },
  { id: "flag-nf", name: "Norfolk Island", url: "/banners/flags/nf.jpg", category: "flags" },
  { id: "flag-ng", name: "Nigeria", url: "/banners/flags/ng.jpg", category: "flags" },
  { id: "flag-ni", name: "Nicaragua", url: "/banners/flags/ni.jpg", category: "flags" },
  { id: "flag-nl", name: "Netherlands", url: "/banners/flags/nl.jpg", category: "flags" },
  { id: "flag-no", name: "Norway", url: "/banners/flags/no.jpg", category: "flags" },
  { id: "flag-np", name: "Nepal", url: "/banners/flags/np.jpg", category: "flags" },
  { id: "flag-nr", name: "Nauru", url: "/banners/flags/nr.jpg", category: "flags" },
  { id: "flag-nu", name: "Niue", url: "/banners/flags/nu.jpg", category: "flags" },
  { id: "flag-nz", name: "New Zealand", url: "/banners/flags/nz.jpg", category: "flags" },
  { id: "flag-om", name: "Oman", url: "/banners/flags/om.jpg", category: "flags" },
  { id: "flag-pa", name: "Panama", url: "/banners/flags/pa.jpg", category: "flags" },
  { id: "flag-pe", name: "Peru", url: "/banners/flags/pe.jpg", category: "flags" },
  { id: "flag-pf", name: "French Polynesia", url: "/banners/flags/pf.jpg", category: "flags" },
  { id: "flag-pg", name: "Papua New Guinea", url: "/banners/flags/pg.jpg", category: "flags" },
  { id: "flag-ph", name: "Philippines", url: "/banners/flags/ph.jpg", category: "flags" },
  { id: "flag-pk", name: "Pakistan", url: "/banners/flags/pk.jpg", category: "flags" },
  { id: "flag-pl", name: "Poland", url: "/banners/flags/pl.jpg", category: "flags" },
  { id: "flag-pm", name: "Saint Pierre and Miquelon", url: "/banners/flags/pm.jpg", category: "flags" },
  { id: "flag-pn", name: "Pitcairn Islands", url: "/banners/flags/pn.jpg", category: "flags" },
  { id: "flag-pr", name: "Puerto Rico", url: "/banners/flags/pr.jpg", category: "flags" },
  { id: "flag-ps", name: "Palestine", url: "/banners/flags/ps.jpg", category: "flags" },
  { id: "flag-pt", name: "Portugal", url: "/banners/flags/pt.jpg", category: "flags" },
  { id: "flag-pw", name: "Palau", url: "/banners/flags/pw.jpg", category: "flags" },
  { id: "flag-py", name: "Paraguay", url: "/banners/flags/py.jpg", category: "flags" },
  { id: "flag-qa", name: "Qatar", url: "/banners/flags/qa.jpg", category: "flags" },
  { id: "flag-re", name: "Réunion", url: "/banners/flags/re.jpg", category: "flags" },
  { id: "flag-ro", name: "Romania", url: "/banners/flags/ro.jpg", category: "flags" },
  { id: "flag-rs", name: "Serbia", url: "/banners/flags/rs.jpg", category: "flags" },
  { id: "flag-ru", name: "Russia", url: "/banners/flags/ru.jpg", category: "flags" },
  { id: "flag-rw", name: "Rwanda", url: "/banners/flags/rw.jpg", category: "flags" },
  { id: "flag-sa", name: "Saudi Arabia", url: "/banners/flags/sa.jpg", category: "flags" },
  { id: "flag-sb", name: "Solomon Islands", url: "/banners/flags/sb.jpg", category: "flags" },
  { id: "flag-sc", name: "Seychelles", url: "/banners/flags/sc.jpg", category: "flags" },
  { id: "flag-sd", name: "Sudan", url: "/banners/flags/sd.jpg", category: "flags" },
  { id: "flag-se", name: "Sweden", url: "/banners/flags/se.jpg", category: "flags" },
  { id: "flag-sg", name: "Singapore", url: "/banners/flags/sg.jpg", category: "flags" },
  { id: "flag-sh", name: "Saint Helena", url: "/banners/flags/sh.jpg", category: "flags" },
  { id: "flag-si", name: "Slovenia", url: "/banners/flags/si.jpg", category: "flags" },
  { id: "flag-sj", name: "Svalbard", url: "/banners/flags/sj.jpg", category: "flags" },
  { id: "flag-sk", name: "Slovakia", url: "/banners/flags/sk.jpg", category: "flags" },
  { id: "flag-sl", name: "Sierra Leone", url: "/banners/flags/sl.jpg", category: "flags" },
  { id: "flag-sm", name: "San Marino", url: "/banners/flags/sm.jpg", category: "flags" },
  { id: "flag-sn", name: "Senegal", url: "/banners/flags/sn.jpg", category: "flags" },
  { id: "flag-so", name: "Somalia", url: "/banners/flags/so.jpg", category: "flags" },
  { id: "flag-sr", name: "Suriname", url: "/banners/flags/sr.jpg", category: "flags" },
  { id: "flag-ss", name: "South Sudan", url: "/banners/flags/ss.jpg", category: "flags" },
  { id: "flag-st", name: "São Tomé and Príncipe", url: "/banners/flags/st.jpg", category: "flags" },
  { id: "flag-sv", name: "El Salvador", url: "/banners/flags/sv.jpg", category: "flags" },
  { id: "flag-sx", name: "Sint Maarten", url: "/banners/flags/sx.jpg", category: "flags" },
  { id: "flag-sy", name: "Syria", url: "/banners/flags/sy.jpg", category: "flags" },
  { id: "flag-sz", name: "Eswatini", url: "/banners/flags/sz.jpg", category: "flags" },
  { id: "flag-tc", name: "Turks and Caicos", url: "/banners/flags/tc.jpg", category: "flags" },
  { id: "flag-td", name: "Chad", url: "/banners/flags/td.jpg", category: "flags" },
  { id: "flag-tf", name: "French Southern Territories", url: "/banners/flags/tf.jpg", category: "flags" },
  { id: "flag-tg", name: "Togo", url: "/banners/flags/tg.jpg", category: "flags" },
  { id: "flag-th", name: "Thailand", url: "/banners/flags/th.jpg", category: "flags" },
  { id: "flag-tj", name: "Tajikistan", url: "/banners/flags/tj.jpg", category: "flags" },
  { id: "flag-tk", name: "Tokelau", url: "/banners/flags/tk.jpg", category: "flags" },
  { id: "flag-tl", name: "Timor-Leste", url: "/banners/flags/tl.jpg", category: "flags" },
  { id: "flag-tm", name: "Turkmenistan", url: "/banners/flags/tm.jpg", category: "flags" },
  { id: "flag-tn", name: "Tunisia", url: "/banners/flags/tn.jpg", category: "flags" },
  { id: "flag-to", name: "Tonga", url: "/banners/flags/to.jpg", category: "flags" },
  { id: "flag-tr", name: "Turkey", url: "/banners/flags/tr.jpg", category: "flags" },
  { id: "flag-tt", name: "Trinidad and Tobago", url: "/banners/flags/tt.jpg", category: "flags" },
  { id: "flag-tv", name: "Tuvalu", url: "/banners/flags/tv.jpg", category: "flags" },
  { id: "flag-tw", name: "Taiwan", url: "/banners/flags/tw.jpg", category: "flags" },
  { id: "flag-tz", name: "Tanzania", url: "/banners/flags/tz.jpg", category: "flags" },
  { id: "flag-ua", name: "Ukraine", url: "/banners/flags/ua.jpg", category: "flags" },
  { id: "flag-ug", name: "Uganda", url: "/banners/flags/ug.jpg", category: "flags" },
  { id: "flag-um", name: "U.S. Outlying Islands", url: "/banners/flags/um.jpg", category: "flags" },
  { id: "flag-us", name: "United States", url: "/banners/flags/us.jpg", category: "flags" },
  { id: "flag-uy", name: "Uruguay", url: "/banners/flags/uy.jpg", category: "flags" },
  { id: "flag-uz", name: "Uzbekistan", url: "/banners/flags/uz.jpg", category: "flags" },
  { id: "flag-va", name: "Vatican City", url: "/banners/flags/va.jpg", category: "flags" },
  { id: "flag-vc", name: "Saint Vincent", url: "/banners/flags/vc.jpg", category: "flags" },
  { id: "flag-ve", name: "Venezuela", url: "/banners/flags/ve.jpg", category: "flags" },
  { id: "flag-vg", name: "British Virgin Islands", url: "/banners/flags/vg.jpg", category: "flags" },
  { id: "flag-vi", name: "U.S. Virgin Islands", url: "/banners/flags/vi.jpg", category: "flags" },
  { id: "flag-vn", name: "Vietnam", url: "/banners/flags/vn.jpg", category: "flags" },
  { id: "flag-vu", name: "Vanuatu", url: "/banners/flags/vu.jpg", category: "flags" },
  { id: "flag-wf", name: "Wallis and Futuna", url: "/banners/flags/wf.jpg", category: "flags" },
  { id: "flag-ws", name: "Samoa", url: "/banners/flags/ws.jpg", category: "flags" },
  { id: "flag-ye", name: "Yemen", url: "/banners/flags/ye.jpg", category: "flags" },
  { id: "flag-yt", name: "Mayotte", url: "/banners/flags/yt.jpg", category: "flags" },
  { id: "flag-za", name: "South Africa", url: "/banners/flags/za.jpg", category: "flags" },
  { id: "flag-zm", name: "Zambia", url: "/banners/flags/zm.jpg", category: "flags" },
  { id: "flag-zw", name: "Zimbabwe", url: "/banners/flags/zw.jpg", category: "flags" },
];

export const ALL_BANNER_PRESETS: BannerPreset[] = [
  ...COLOR_BANNERS,
  ...MUSIC_BANNERS,
  ...FLAG_BANNERS,
];
